export const HOME_SEARCH_ACTION_BEGIN = 'HOME_SEARCH_ACTION_BEGIN';
export const HOME_SEARCH_ACTION_SUCCESS = 'HOME_SEARCH_ACTION_SUCCESS';
export const HOME_SEARCH_ACTION_FAILURE = 'HOME_SEARCH_ACTION_FAILURE';
export const HOME_SEARCH_ACTION_DISMISS_ERROR = 'HOME_SEARCH_ACTION_DISMISS_ERROR';
export const HOME_CLICK_SERIE_DETAILS = 'HOME_CLICK_SERIE_DETAILS';
export const HOME_GET_SIMILAR_ITEMS_BEGIN = 'HOME_GET_SIMILAR_ITEMS_BEGIN';
export const HOME_GET_SIMILAR_ITEMS_SUCCESS = 'HOME_GET_SIMILAR_ITEMS_SUCCESS';
export const HOME_GET_SIMILAR_ITEMS_FAILURE = 'HOME_GET_SIMILAR_ITEMS_FAILURE';
export const HOME_GET_SIMILAR_ITEMS_DISMISS_ERROR = 'HOME_GET_SIMILAR_ITEMS_DISMISS_ERROR';
export const HOME_GET_RECENT_SERIE_BEGIN = 'HOME_GET_RECENT_SERIE_BEGIN';
export const HOME_GET_RECENT_SERIE_SUCCESS = 'HOME_GET_RECENT_SERIE_SUCCESS';
export const HOME_GET_RECENT_SERIE_FAILURE = 'HOME_GET_RECENT_SERIE_FAILURE';
export const HOME_GET_RECENT_SERIE_DISMISS_ERROR = 'HOME_GET_RECENT_SERIE_DISMISS_ERROR';
export const HOME_OPEN_MODAL_SIGN_OR_CONNECT = 'HOME_OPEN_MODAL_SIGN_OR_CONNECT';
export const HOME_REGISTER_USER = 'HOME_REGISTER_USER';
export const HOME_VOTE_BEGIN = 'HOME_VOTE_BEGIN';
export const HOME_VOTE_SUCCESS = 'HOME_VOTE_SUCCESS';
export const HOME_VOTE_FAILURE = 'HOME_VOTE_FAILURE';
export const HOME_VOTE_DISMISS_ERROR = 'HOME_VOTE_DISMISS_ERROR';
export const HOME_GET_COMPUTE_BEGIN = 'HOME_GET_COMPUTE_BEGIN';
export const HOME_GET_COMPUTE_SUCCESS = 'HOME_GET_COMPUTE_SUCCESS';
export const HOME_GET_COMPUTE_FAILURE = 'HOME_GET_COMPUTE_FAILURE';
export const HOME_GET_COMPUTE_DISMISS_ERROR = 'HOME_GET_COMPUTE_DISMISS_ERROR';
export const HOME_GET_ALL_SERIES_BEGIN = 'HOME_GET_ALL_SERIES_BEGIN';
export const HOME_GET_ALL_SERIES_SUCCESS = 'HOME_GET_ALL_SERIES_SUCCESS';
export const HOME_GET_ALL_SERIES_FAILURE = 'HOME_GET_ALL_SERIES_FAILURE';
export const HOME_GET_ALL_SERIES_DISMISS_ERROR = 'HOME_GET_ALL_SERIES_DISMISS_ERROR';
export const HOME_BACK_TO_COMPUTE = 'HOME_BACK_TO_COMPUTE';
export const HOME_GET_ALL_SERIE_BEGIN = 'HOME_GET_ALL_SERIE_BEGIN';
export const HOME_GET_ALL_SERIE_SUCCESS = 'HOME_GET_ALL_SERIE_SUCCESS';
export const HOME_GET_ALL_SERIE_FAILURE = 'HOME_GET_ALL_SERIE_FAILURE';
export const HOME_GET_ALL_SERIE_DISMISS_ERROR = 'HOME_GET_ALL_SERIE_DISMISS_ERROR';




