const initialState = {
  token: "",
  baseApiUrl: 'http://127.0.0.1:8000/',
  resultatRecherche: [],
  typeApp: 'search',
  cloudWords: [],
  resultatCompute: [],
  allSeries: {},
  showDetails: null,
  getSimilarItemsPending: false,
  getSimilarItemsError: null,
  getRecentSeriePending: false,
  getRecentSerieError: null,
  modalSignOrConnect: false,
  votePending: false,
  voteError: null,
  voteSuccess:false,
  getAllSeriePending: false,
  getAllSerieError: null,
  getComputePending: false,
  getComputeError: null,
  getMyUserVotePending: false,
  getMyUserVoteError: null,
  getMyVoteComputePending: false,
  getMyVoteComputeError: null,
  deleteVotePending: false,
  deleteVoteError: null,
  deleteVoteSuccess: false,
  searchCountPending: false,
  searchCountError: null,


};

export default initialState;
