const initialState = {
  token: "",
  baseApiUrl: '',
  resultatRecherche: [],
  typeApp: '',
  cloudWords: [],
  resultatCompute: [],
  allSeries: {},
  showDetails: null,
  getSimilarItemsPending: false,
  getSimilarItemsError: null,
  getRecentSeriePending: false,
  getRecentSerieError: null,
  modalSignOrConnect: false,
  votePending: false,
  voteError: null,
  voteSuccess:false,
  getAllSeriePending: false,
  getAllSerieError: null,
  getComputePending: false,
  getComputeError: null,
  getMyUserVotePending: false,
  getMyUserVoteError: null,
  getMyVoteComputePending: false,
  getMyVoteComputeError: null,
  deleteVotePending: false,
  deleteVoteError: null,
  deleteVoteSuccess: false,
  searchCountPending: false,
  searchCountError: null,
  getMostLikedPending: false,
  getMostLikedError: null,
  getWordsOfSeriePending: false,
  getWordsOfSerieError: null,
  uploadSeriePending: false,
  uploadSerieError: null,
  searchActionSucess: null,
  searchText: '',
  totoPending: false,
  totoError: null,


};

export default initialState;
